### ISSUE TITLE
Senmanga mangas not loading

### ISSUE THREAD

**Issue by Kleankyrie2** [rintendou/tommys-extensions#4]
![64E52B5A-DFD4-4093-A0D8-6EBF43880BA5](https://user-images.githubusercontent.com/120565949/208797526-ad40442f-18d5-4410-97f9-2f9f452c38d1.jpeg)

Is there a fix? thanks

**Comment by rintendou** [comment]
Are the thumbnails not loading or everything is not loading?

**Comment by Kleankyrie2** [comment]
everything is not loading in paperback

**Comment by rintendou** [comment]
Fixed loading issue with chapters, should allow for you to read now. View more is still not working however. Will work on that ASAP.
